### ISSUE TITLE
mplcursors don't work with cartopy

### ISSUE THREAD

**Issue by yt87** [anntzer/mplcursors#13]
There are several issues with mplcursors ant cartopy (https://scitools.org.uk/cartopy/docs/v0.17/index.html). Here is a script that illustrates those issues:
```
import os
import sys
import numpy as np
from cartopy import config
import cartopy.feature as cfeature
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
from mplcursors import cursor

def ex1():
    ax = plt.axes(projection=ccrs.Mollweide())
    #ax.set_extent(np.array([-180, 180, -90, 90]) * 1e5)
    ax.stock_img()
    p = ax.coastlines()
    g_lon, g_lat = 19, 50
    a_lon, a_lat = -150, 61
    line = ax.plot([g_lon, a_lon], [g_lat, a_lat], 'ro-', transform=ccrs.Geodetic())
    c = cursor(line)

def ex2():
    fig = plt.figure(figsize=(8, 12))

    # get the path of the file. It can be found in the repo data directory.
    fname = os.path.join(config["repo_data_dir"],
                         'raster', 'sample', 'Miriam.A2012270.2050.2km.jpg'
                        )
    img_extent = (-120.67660000000001, -106.32104523100001,
                  13.2301484511245, 30.766899999999502)
    img = plt.imread(fname)

    ax = plt.axes(projection=ccrs.PlateCarree())
    plt.title('Hurricane Miriam from the Aqua/MODIS satellite\n'
              '2012 09/26/2012 20:50 UTC')

    # set a margin around the data
    ax.set_xmargin(0.05)
    ax.set_ymargin(0.10)

    # add the image. Because this image was a tif, the "origin" of the image
    # is in the upper left corner
    ax.imshow(img, origin='upper', extent=img_extent,
              transform=ccrs.PlateCarree())
    ax.coastlines(resolution='50m', color='black', linewidth=1)

    # mark a known place to help us geo-locate ourselves
    ax.plot(-117.1625, 32.715, 'bo', markersize=7, transform=ccrs.Geodetic())
    ax.text(-117, 33, 'San Diego', transform=ccrs.Geodetic())
    c = cursor(ax)

def ex3():
    def fmt(u, v):
        w = u + 1j * v
        ws = np.abs(w)
        wd = np.angle(w, deg=True)
        return '{:.1f} {:.0f}'.format(ws, 270-wd)

    fig = plt.figure(figsize=(8, 6))
    ak_west = -170
    ak_east = -130
    ak_south = 52
    ak_north = 72
    central_longitude = -150
    true_scale_latitude = 60
    wlon = np.array([[-170, -140], [-170, -140]]) 
    wlat = np.array([[68, 68], [63, 63]]) 
    wu = np.array([[0, 10], [10, 0]])
    wv = np.array([[10, 0], [0, 10]])
    w = zip(wu.flatten(), wv.flatten())
    labels = [fmt(u, v) for (u, v) in w]
    proj = ccrs.NorthPolarStereo(central_longitude=central_longitude,
                                 true_scale_latitude=true_scale_latitude)
    ax = fig.add_subplot(1, 1, 1, projection=proj)
    ax.set_extent([ak_west, ak_east, ak_south, ak_north])
    ax.gridlines(xlocs=range(-190, -109, 10), ylocs=range(50, 76, 5))
    ax.add_feature(cfeature.LAND, alpha=0.2)
    ax.add_feature(cfeature.OCEAN, alpha=0.3);
    ax.add_feature(cfeature.BORDERS);
    barbs = ax.barbs(wlon, wlat, wu, wv, transform=ccrs.PlateCarree(),
                     length=10, linewidth=2)

    def cact(sel):
        return sel.annotation.set_text(labels[sel.target.index])

    c = cursor(barbs)
    c.connect('add', cact)

ex = [ex1, ex2, ex3]

ex[int(sys.argv[1])-1]()
plt.show()
```
Example 1 runs fine:
`> python examples.py `
The line annotation is displayed correctly.

An attempt to get location on the image in example 2 produces an error:
```
> python examples.py 2
Traceback (most recent call last):
  File "/home/george.trojan/miniconda3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 215, in process
    func(*args, **kwargs)
  File "/home/george.trojan/miniconda3/lib/python3.7/site-packages/mplcursors/_mplcursors.py", line 441, in _nonhover_handler
    self._on_select_button_press(event)
  File "/home/george.trojan/miniconda3/lib/python3.7/site-packages/mplcursors/_mplcursors.py", line 476, in _on_select_button_press
    pi = _pick_info.compute_pick(artist, per_axes_event[artist.axes])
  File "/home/george.trojan/miniconda3/lib/python3.7/functools.py", line 824, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/george.trojan/miniconda3/lib/python3.7/site-packages/mplcursors/_pick_info.py", line 370, in _
    idxs = ((xy - low) / (high - low) * ns).astype(int)[::-1]
ValueError: operands could not be broadcast together with shapes (2,) (3,)
```
The same error would show in example 1 as well if the cursor was tracking all artists associated with the axes, i.e. when `cursor(line)` is replaced by `cursor(ax)`.

In example 3 the wind barbs cannot be labeled.

I made an attempt to fix the code, the only changes are in file `_pick_info.py`. Here is a diff on the "fix":

```
> diff _pick_info.py _pick_info.py.orig
325a326
>         ax = artist.axes
328,330c329,330
<         # GT fix
<         offsets = artist.get_offset_transform().transform(offsets)
<         ds = np.hypot(*(offsets - [event.x, event.y]).T)
---
>         ds = np.hypot(*(ax.transData.transform(offsets)
>                         - [event.x, event.y]).T)
332,333c332
<         offsets = artist.axes.transData.inverted().transform(offsets[argmin])
<         target = with_attrs(offsets, index=inds[argmin])
---
>         target = with_attrs(offsets[argmin], index=inds[argmin])
364,365c363
<     # GT fix: 3rd coordinate might be colours and transparency
<     ns = np.asarray(artist.get_array().shape[:2])[::-1]  # (y, x) -> (x, y)
---
>     ns = np.asarray(artist.get_array().shape)[::-1]  # (y, x) -> (x, y)
381,383c379,380
<     # GT fix
<     offsets = artist.get_offset_transform().transform(offsets)
<     ds = np.hypot(*(offsets - [event.x, event.y]).T)
---
>     ds = np.hypot(
>         *(artist.axes.transData.transform(offsets) - [event.x, event.y]).T)
386,387c383
<         offsets = artist.axes.transData.inverted().transform(offsets[argmin])
<         target = with_attrs(offsets, index=argmin)
---
>         target = with_attrs(offsets[argmin], index=argmin)
```

The error in example2 is trivial: the artist (image) can be 2 or 3 dimensional array, only first 2 matter. To fix example 3 one has to use artist transform, not `transData`. Similar fix is needed to label scatter plot. 

I doubt I have caught everything. 

Cartopy and mplcursors are from conda-forge:
```
> conda list mplcursors
# packages in environment at /home/george.trojan/miniconda3:                   
#                                                                              
# Name                    Version                   Build  Channel             
mplcursors                0.2.1                      py_0    conda-forge       
(base) pointyhaired@gtrojan> conda list cartopy
# packages in environment at /home/george.trojan/miniconda3:                   
#
# Name                    Version                   Build  Channel
cartopy                   0.17.0          py37h0aa2c8f_1004    conda-forge
```

**Comment by anntzer** [comment]
Thanks.  I haven't looked at this in detail, but I guess it mostly makes sense.

**Comment by anntzer** [comment]
Also, can you try with master?  Looks like some of your fixes overlap with recent commits, e.g. https://github.com/anntzer/mplcursors/commit/71c7d1004675270483c7d79dc97b6bb5dbbe2c68.

**Comment by yt87** [comment]
Example 1 works now. There is a new bug: example 2 raises TypeError. I've added `print` to `_format_scalarmappable_value`, just before `return`
```
value = artist.get_array()[idx]
    print('======', value)
    return ("["
            + _strip_math(
                artist.colorbar.formatter.format_data_short(value).strip())
            + "]")
```

The result is:
```
> python intro.py 2
====== [41 52 74]
Traceback (most recent call last):
  File "/home/gtrojan/miniconda3/envs/cursors/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 215, in process
    func(*args, **kwargs)
  File "/home/gtrojan/miniconda3/envs/cursors/lib/python3.7/site-packages/mplcursors/_mplcursors.py", line 458, in _nonhover_handler
    self._on_select_button_press(event)
  File "/home/gtrojan/miniconda3/envs/cursors/lib/python3.7/site-packages/mplcursors/_mplcursors.py", line 500, in _on_select_button_press
    self.add_selection(min(pis, key=lambda pi: pi.dist))
  File "/home/gtrojan/miniconda3/envs/cursors/lib/python3.7/site-packages/mplcursors/_mplcursors.py", line 308, in add_selection
    _pick_info.get_ann_text(*pi), xy=pi.target,
  File "/home/gtrojan/miniconda3/envs/cursors/lib/python3.7/functools.py", line 824, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/gtrojan/miniconda3/envs/cursors/lib/python3.7/site-packages/mplcursors/_pick_info.py", line 486, in wrapper
    return func(sel, **extra_kw)
  File "/home/gtrojan/miniconda3/envs/cursors/lib/python3.7/site-packages/mplcursors/_pick_info.py", line 570, in _
    cursor_text = _format_scalarmappable_value(artist, sel.target.index)
  File "/home/gtrojan/miniconda3/envs/cursors/lib/python3.7/site-packages/mplcursors/_pick_info.py", line 537, in _format_scalarmappable_value
    + "]")
  File "/home/gtrojan/miniconda3/envs/cursors/lib/python3.7/site-packages/matplotlib/ticker.py", line 604, in format_data_short
    return '%-12g' % value
  File "/home/gtrojan/miniconda3/envs/cursors/lib/python3.7/site-packages/numpy/ma/core.py", line 4296, in __float__
    raise TypeError("Only length-1 arrays can be converted "
TypeError: Only length-1 arrays can be converted to Python scalars
```

**Comment by anntzer** [comment]
I just pushed some fixes based on your suggested patch, can you give a try to master? 
Everything should be fixed now.

**Comment by yt87** [comment]
I found one more case the code needs modification.

In example 1 of my first comment, when the endpoint of the great circle segment is selected, annotation is made at the longitude-latitude (not map projection) coordinates, that is near the centre of the globe. My (very dirty) fix is (starting at line 267 of `_pick_info.py`):

```
if artist.get_marker() not in ["None", "none", " ", "", None]:
        # GT: save for later
        #ds = np.hypot(*(xy - artist.get_transform().transform(data_xy)).T)
        xy1 = artist.get_transform().transform(data_xy)
        ds = np.hypot(*(xy - xy1).T)
        try:
            argmin = np.nanargmin(ds)
            dmin = ds[argmin]
        except (ValueError, IndexError):
            # numpy 1.7.0's `nanargmin([nan])` returns nan, so
            # `ds[argmin]` raises IndexError.  In later versions of numpy,
            # `nanargmin([nan])` raises ValueError (the release notes for 1.8.0
            # are incorrect on this topic).
            pass
        else:
            # GT: have to transform back
            # More precise than transforming back.
            xy2 = artist.axes.transData.inverted().transform(xy1)
            target = _with_attrs(xy2[argmin], index=argmin)
            #target = _with_attrs(artist.get_xydata()[argmin], index=argmin)
            sels.append(Selection(artist, target, dmin, None, None))
```
On another note: annotations on an image are not draggable. I think this could be done with the help of `key_press_event`, although I am not sure it is worth doing.

**Comment by anntzer** [comment]
Thanks.
I pushed your fix (and some more) to master.
As for dragging on images, I think this is basically point (2) of https://github.com/anntzer/mplcursors/issues/10#issuecomment-451768593? (see my reply in that thread)

**Comment by yt87** [comment]
Now it works. Thanks.
I found something else, likely not related to cartopy, however the confusing behaviour can be illustrates with the help of my example 1:

Add `multiple=True` to the cursor instantiation.
Select 3 points so the labels are partially overlapping, let's call them A, B and C
Move labels for each point. Sometimes it works as expected. On some occasions, two or three move together, even when all labels are clearly separated. For example, labels for A and B can be moved independently, but moving C also changes location for B. I can't see a pattern.

Just a thought: cartopy splits the two-point line into segments to approximate the shortest route on the globe. maybe the logic in compute_pick for Line2D does not handle this case well?

**Comment by anntzer** [comment]
I guess the bug you report may be fixed by https://github.com/matplotlib/matplotlib/pull/7894?  Unfortunately, I was not able to understand that PR, despite spending some time on it.

**Comment by yt87** [comment]
Yes, it can. I added few print statements to the current (3.0.3) matplotlib file `offsetbox.py`, class `DraggableBase`:
```
def __init__(self, ref_artist, use_blit=False):
        self.ref_artist = ref_artist
        self.got_artist = False
        self.got_other_artist = 0
        print('========1', ref_artist, id(ref_artist), id(self.ref_artist))
        self.canvas = self.ref_artist.figure.canvas
```
```
 def on_pick(self, evt):
        print('========2', id(evt), id(evt.artist)%1000,
              id(self.ref_artist)%1000)
        #if self.got_other_artist:
        #    print('====---------------3', self.got_other_artist)
        #    return
        if self._check_still_parented() and evt.artist == self.ref_artist:
            print('====---------------4', id(evt.artist)%1000)

            self.mouse_x = evt.mouseevent.x
            self.mouse_y = evt.mouseevent.y
            self.got_artist = True

            if self._use_blit:
                self.ref_artist.set_animated(True)
                self.canvas.draw()
                self.background = self.canvas.copy_from_bbox(
                                    self.ref_artist.figure.bbox)
                self.ref_artist.draw(self.ref_artist.figure._cachedRenderer)
                self.canvas.blit(self.ref_artist.figure.bbox)
                self._c1 = self.canvas.mpl_connect('motion_notify_event',
                                                   self.on_motion_blit)
            else:
                self._c1 = self.canvas.mpl_connect('motion_notify_event',
                                                   self.on_motion)
            self.save_offset()
        else:
            self.got_other_artist = id(evt.artist)
        print('====-----------------5', self.got_other_artist%1000)
```
The test code is still using cartopy, although I think it could be just plot of a single line.
```
import os
import sys
import numpy as np
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
from mplcursors import cursor

def f(proj):
    ax = plt.axes(projection=proj)
    p = ax.coastlines()
    g_lon, g_lat = 19, 50
    a_lon, a_lat = -150, 61
    line, = ax.plot([g_lon, a_lon], [g_lat, a_lat], 'ro-',
                    transform=ccrs.Geodetic())
    c = cursor(line, multiple=True)
    plt.show()

i = int(sys.argv[1])
proj = {0: ccrs.PlateCarree(),
        1: ccrs.Mercator(),
        2: ccrs.NorthPolarStereo(central_longitude=-90,
                                 true_scale_latitude = 60),
        }
f(proj[i])
```
Select 3 points, such that the labels overlap (called A, B and C), between Norway coast and Svalbard:
```
(expr) [gtrojan@asok test]$ python mplcursor.py 2
========1 Annotation(2.24773e+06, 603402, '2.248e+06\n6.034e+05\n(67.934680°N\n15.026759°E)') 140457974615008 140457974615008
========1 Annotation(1.71062e+06, 369099, '1.711e+06\n3.691e+05\n(73.322404°N\n12.175972°E)') 140457869198560 140457869198560
========1 Annotation(1.20428e+06, 148213, '1.204e+06\n1.482e+05\n(78.395702°N\n7.016255°E)') 140457869229080 140457869229080
```
Mouse click at the right upper corner of A produces
```
========2 140457869229304 8 8
====---------------4 8
====-----------------5 0
========2 140457869229304 8 560
====-----------------5 8
========2 140457869229304 8 80
====-----------------5 8
```
Click within intersection of A and B:
```
========2 140457868835248 8 8
====---------------4 8
====-----------------5 0
========2 140457868835248 8 560
====-----------------5 8
========2 140457868835248 8 80
====-----------------5 8
========2 140457868834968 560 8
====-----------------5 560
========2 140457868834968 560 560
====---------------4 560
====-----------------5 8
========2 140457868834968 560 80
====-----------------5 560
```
Both A and B are dragged. The match is 8, 8 and 560, 560.
Selection at the intersection of A, B and C prints
```
========2 140457868891024 8 8
====---------------4 8
====-----------------5 0
========2 140457868891024 8 560
====-----------------5 8
========2 140457868891024 8 80
====-----------------5 8
========2 140457868893936 560 8
====-----------------5 560
========2 140457868893936 560 560
====---------------4 560
====-----------------5 8
========2 140457868893936 560 80
====-----------------5 560
========2 140457868891136 80 8
====-----------------5 80
========2 140457868891136 80 560
====-----------------5 80
========2 140457868891136 80 80
====---------------4 80
====-----------------5 560
```
There are 3 matches: 140457868891024 8 8, 140457868893936 560 560 and 140457868891136 80 80, all 3 labels move together. This could be considered a desired behaviour.
Problematic is selection of left upper corner of B (but some distance from the corner):
```
========2 140457868615296 8 8
====---------------4 8
====-----------------5 0
========2 140457868615296 8 560
====-----------------5 8
========2 140457868615296 8 80
====-----------------5 8
========2 140457868611768 560 8
====-----------------5 560
========2 140457868611768 560 560
====---------------4 560
====-----------------5 8
========2 140457868611768 560 80
====-----------------5 560
========2 140457868614456 80 8
====-----------------5 80
========2 140457868614456 80 560
====-----------------5 80
========2 140457868614456 80 80
====---------------4 80
====-----------------5 560
```
Lower right corner looks right for some reason.

matplotlib/matplotlib#7894 fix forces selection of a single label. If the three `if` statement lines in `on_pick` are uncommented, the "problematic" case prints
```
========2 140498948813320 424 424
====---------------4 424
====-----------------5 0
========2 140498948813320 424 200
====-----------------5 424
========2 140498948813320 424 952
====-----------------5 424
========2 140498948813656 200 424
====-----------------5 200
========2 140498948813656 200 200
====---------------3 140498948914424
========2 140498948813656 200 952
====---------------3 140498948914424
```
This is not quite right, because A is moved.
It also possible to trigger pick event away from plotted line/labels. This seems to be a real issue.

**Comment by yt87** [comment]
OK, the real issue is that annotation pick area is a rectangle which contains both the text and the arrow. Not intuitive when it comes to moving the object. I think users expect the highlighted text as a handle.

**Comment by anntzer** [comment]
Is it still the case on mpl master?  There's https://github.com/matplotlib/matplotlib/issues/10875 and https://github.com/matplotlib/matplotlib/pull/13708 although I lost track of the current status.

**Comment by yt87** [comment]
According to @dstansby and @tacasswell on matplotlib/matplotlib#10875 is fixed on v3.1.x. I am not sure this will resolve the original issue in matplotlib/matplotlib#7894. When there are several annotations close by it is difficult to visualise the rectangles. IMHO the area should be just the extent of "hello" and possibly the arrow line (to allow to split annotations for two distinct points with overlapping text).
In any case I would recommend to reject @fukatani solution. It helps, but it is not the "real" fix.

**Comment by anntzer** [comment]
My point is mostly that this picking code is entirely on matplotlib's side, not something that can really be changed on mplcursors side (unless I reimplement the entire drag-annotation stack, which seems a bit silly).
You should probably leave your comment on the threads in matplotlib's repo, so that they are not lost.

**Comment by yt87** [comment]
@anntzer, you did create a link to this thread on matplotlib/matplotlib#13708. Unfortunately I don't have write access.
BTW, my use case is https://www.weather.gov/aawu/, icing, turbulence and convection. That has been written ~7 years ago, I need to update the code to python 3, and cartopy replacing basemap.

**Comment by anntzer** [comment]
OK, I think this issue on this side can be closed, as there's nothing else to be done here?
Always happy to see more use cases for mplcursors :)

**Comment by yt87** [comment]
I agree.

**Comment by anntzer** [comment]
@yt87 I am considering adding a "list of users" section to the docs; is your code that uses mplcursors available somewhere? Either way, please let me know.
