### ISSUE TITLE
Problem with displaying artist's label instead of x,y

### ISSUE THREAD

**Issue by siddharthakongara** [anntzer/mplcursors#6]
Hi

I'm trying the example https://mplcursors.readthedocs.io/en/latest/examples/artist_labels.html on python3, matplotlib 2.2.2

On clicking a line I get the following error:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 388, in process
    proxy(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 228, in __call__
    return mtd(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mplcursors/_mplcursors.py", line 434, in _nonhover_handler
    self._on_select_button_press(event)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mplcursors/_mplcursors.py", line 474, in _on_select_button_press
    self.add_selection(min(pis, key=lambda pi: pi.dist))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mplcursors/_mplcursors.py", line 355, in add_selection
    figure.canvas.blit()
TypeError: blit() missing 1 required positional argument: 'bbox'

**Comment by anntzer** [comment]
Thank you for the report.  Turns out the MacOSX backend behaves a bit differently from the others, but the issue should be fixed as of master.  Can you give it a try?

**Comment by siddharthakongara** [comment]
Indeed it has! thanks!
