### ISSUE TITLE
Exception transData

### ISSUE THREAD

**Issue by eyalk11** [anntzer/mplcursors#62]
```
Traceback (most recent call last):
  File "C:\Users\ekarni\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\cbook\__init__.py", line 287, in process
    func(*args, **kwargs)
  File "C:\Users\ekarni\AppData\Local\Programs\Python\Python39\lib\site-packages\mplcursors\_mplcursors.py", line 537, in _hover_handler
    self._on_select_event(event)
  File "C:\Users\ekarni\AppData\Local\Programs\Python\Python39\lib\site-packages\mplcursors\_mplcursors.py", line 565, in _on_select_event
    pi = _pick_info.compute_pick(artist, per_axes_event[artist.axes])
  File "C:\Users\ekarni\AppData\Local\Programs\Python\Python39\lib\functools.py", line 877, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Users\ekarni\AppData\Local\Programs\Python\Python39\lib\site-packages\mplcursors\_pick_info.py", line 304, in _
    sel = _compute_projection_pick(artist, artist.get_path(), xy)
  File "C:\Users\ekarni\AppData\Local\Programs\Python\Python39\lib\site-packages\mplcursors\_pick_info.py", line 251, in _compute_projection_pick
    artist.axes.transData.inverted().transform(projs[argmin]))
AttributeError: 'NoneType' object has no attribute 'transData'

```

It probably happened while the graph was generating. I have no more details to share.

**Comment by anntzer** [comment]
In mplcursors 0.4 this line was already protected by an early exit `if artist.axes is None` (in _on_select_event), so it's hard for me to see how this can happen.  In the absence of further details I can only close this as non-actionable; feel free to re-ping with more details.
