### ISSUE TITLE
Duplicate cursors when toggling a plot

### ISSUE THREAD

**Issue by ohshitgorillas** [anntzer/mplcursors#77]
I am creating data reduction software and, in one section, I am showing four plots loaded up with a lot of data (this is for outlier detection and removal, so the plot being a clusterfuck is a good thing). Here's an example screenshot:

![Screenshot 2024-05-26 192257](https://github.com/anntzer/mplcursors/assets/96808410/26f78a45-77a9-4884-b59d-d7a54d918e20)

The user should be able to hover the mouse over an individual line and see the analysis label. The user also has a button to toggle the lower right-hand plot between 2 amu (hydrogen) and 40 amu (argon), both equally useless in 95% of cases.

Both of these features work well in isolation, however, combined they have a tendency to be unpredictable: sometimes I see one hover indicator, sometimes I see two or three, sometimes two in different plots, sometimes two pointing to the same analysis. Here's an example (please ignore the wonkiness in the axis plotting/overlapping, my autotest feature doesn't work 100%):

![Screenshot 2024-05-27 145556](https://github.com/anntzer/mplcursors/assets/96808410/1d1d11a8-a396-4ca8-a8d1-d3db872cb851)

The cursor and button are defined in the code like this:

```
    # create mplcursors instance and connect to hover events
    cursor = mplcursors.cursor(lines_to_analyze.keys(), hover=True)
    cursor.connect("add", lambda sel: sel.annotation.set_text(lines_to_analyze[sel.artist].analysis_label))

    # create the toggle button
    global toggle_button # do not remove-prevents garbage collection
    button_axes = figure.add_axes([0.8885, 0.467, 0.1, 0.04])
    toggle_button = Button(button_axes, label='Toggle 2/40 amu', color='1')
    toggle_button.on_clicked(lambda event: on_click(event, cursor, filtered_data, axes, lines_to_analyze, canvas, show_40_amu))
```

When the user clicks the toggle 2/40 amu button and switches to the other plot, I disconnect the old click handler, and create a new one:

```
def on_click(event, cursor, filtered_data, axes, lines_to_analyze, canvas, show_40_amu):
    # toggle the bool
    show_40_amu.set(not show_40_amu.get())

    # clear the lines and axes from the bottom right plot
    axes[1, 1].clear()
    for line in list(lines_to_analyze.keys()):
        if line in axes[1, 1].lines:
            del lines_to_analyze[line]

    # determine the mass to show, and the new title
    mass = '40 amu' if show_40_amu.get() else '2 amu'
    new_title = '40 amu - All Data' if show_40_amu.get() else '2 amu - All Data'
    
    # plot the new data
    for analysis in filtered_data:
        
        # filter data for active indices
        active_indices = analysis.data_status[mass].to_numpy().flatten()
        x = analysis.time_sec[active_indices==1]
        y = analysis.raw_data[mass][active_indices==1]
        
        # draw the lines
        line_color  = 'blue' if analysis.active else 'gray'
        line_marker = 'o' if analysis.active else 'x'
        line, = axes[1,1].plot(x, y, marker=line_marker, linestyle='-', picker=5, color=line_color, zorder=2)
        
        # update lines to analyze
        lines_to_analyze[line] = analysis

    valid_lines = [line for line in lines_to_analyze.keys() if line.figure is not None]
    
    # disconnect and recreate the hover
    cursor.remove()
    cursor = mplcursors.cursor(valid_lines, hover=True)
    cursor.connect("add", lambda sel: sel.annotation.set_text(lines_to_analyze[sel.artist].analysis_label))
    
    canvas.draw()
```
As you might imagine, I've had a hell of a time reproducing this, but I have managed with the following script (proof is in the screenshot below):

```
import mplcursors
import tkinter as tk
import matplotlib.pyplot as plt
from matplotlib.widgets import Button
import random

# lines to plot
lines = {}

# Create the figure and subplots
fig, axes = plt.subplots(2, 2)
fig.set_size_inches(13, 9)
# Create some sample data
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y = {}
y_new = {}
for i in range(1, 101):
    y[i]     = [random.randint(1, 10) for _ in range(len(x))]
    y_new[i] = [random.randint(1, 10) for _ in range(len(x))]

# create a boolean var for toggling between y and y_new in 1,1
show_y_new = tk.BooleanVar(False)

# Plot the normal data on each subplot
for i in range(2):
    for j in range(2):
        for k in range(1, 101):
            line, = axes[i, j].plot(x, y[k], label=f'Line {k}')
            lines[line] = line
                
# Create a cursor for hover indicators
cursor = mplcursors.cursor(lines, hover=True)
cursor.connect("add")
def on_hover(sel):
    x, y = sel.target
    sel.annotation.set_text(f"({x:.2f}, {y:.2f})")

# create a button to toggle the 1,1 subplot between y and y_new
def on_click(cursor):
    show_y_new.set(not show_y_new.get())
    if show_y_new.get():
        for line in lines:
            if line.axes == axes[1, 1]:
                line.set_ydata(y_new[int(line.get_label().split(' ')[1])])
    else:
        for line in lines:
            if line.axes == axes[1, 1]:
                line.set_ydata(y[int(line.get_label().split(' ')[1])])
            
    valid_lines = [line for line in lines.values() if line.figure is not None]
    plt.draw()
    cursor.remove()
    cursor = mplcursors.cursor(valid_lines, hover=True)
    cursor.connect("add", on_hover)

# Create the button
global button # do not remove-prevents garbage collection
button_axes = fig.add_axes([0.8885, 0.467, 0.1, 0.04])
button = Button(button_axes, label='Toggle 1,1 data')
button.on_clicked(lambda event: on_click(cursor))

# Show the plot
plt.show()
```

![Screenshot 2024-05-27 161459](https://github.com/anntzer/mplcursors/assets/96808410/6ba42782-9009-4df7-b88a-0c8107c21654)

I'd be lying if I said it was easy to reproduce this, even with the above script, however, it is possible when toggling the plot. You have to move the mouse relatively quickly. Increasing the number of lines to 200 may help.

How can I prevent mplcursors from showing multiple hover indicators?

**Comment by anntzer** [comment]
With your (last) script I get
```
Traceback (most recent call last):
  File "/tmp/test.py", line 22, in <module>
    show_y_new = tk.BooleanVar(False)
                 ^^^^^^^^^^^^^^^^^^^^
  File ".../tkinter/__init__.py", line 632, in __init__
    Variable.__init__(self, master, value, name)
  File ".../tkinter/__init__.py", line 394, in __init__
    self._root = master._root()
                 ^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute '_root'
```
Perhaps a typo somewhere?  Or a specific version of python may be needed.

**Comment by ohshitgorillas** [comment]
I see, the problem with setting the tk bool was that the tk window didn't exist yet. Here's a version that sets the plots inside of a custom tkinter window, which allows setting tk bool vars.

```
import random
import mplcursors
import customtkinter as ctk
from matplotlib.figure import Figure
from matplotlib.widgets import Button
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg

# create the window and frames
window       = ctk.CTk()
data_frame   = ctk.CTkFrame(window)
button_frame = ctk.CTkFrame(window)
data_frame.pack(side=ctk.TOP)
button_frame.pack(side=ctk.BOTTOM)

# lines to plot
lines = {}

# Create the figure and subplots
fig = Figure(figsize=(13, 9), tight_layout=True)
canvas = FigureCanvasTkAgg(fig, master=data_frame)
canvas.draw()
canvas.get_tk_widget().pack(side=ctk.TOP, fill=ctk.BOTH, expand=True)
axes = fig.subplots(2, 2)

# Create some sample data
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y = {}
y_new = {}
for i in range(1, 101):
    y[i]     = [random.randint(1, 10) for _ in range(len(x))]
    y_new[i] = [random.randint(1, 10) for _ in range(len(x))]

# create a boolean var for toggling between y and y_new in 1,1
show_y_new = ctk.BooleanVar(False)

# Plot the normal data on each subplot
for i in range(2):
    for j in range(2):
        for k in range(1, 101):
            line, = axes[i, j].plot(x, y[k], label=f'Line {k}')
            lines[line] = line
                
# Create a cursor for hover indicators
cursor = mplcursors.cursor(lines, hover=True)
cursor.connect("add")
def on_hover(sel):
    x, y = sel.target
    sel.annotation.set_text(f"({x:.2f}, {y:.2f})")

# create a button to toggle the 1,1 subplot between y and y_new
def on_click(cursor):
    show_y_new.set(not show_y_new.get())
    if show_y_new.get():
        for line in lines:
            if line.axes == axes[1, 1]:
                line.set_ydata(y_new[int(line.get_label().split(' ')[1])])
    else:
        for line in lines:
            if line.axes == axes[1, 1]:
                line.set_ydata(y[int(line.get_label().split(' ')[1])])
            
    valid_lines = [line for line in lines.values() if line.figure is not None]
    canvas.draw()
    cursor.remove()
    cursor = mplcursors.cursor(valid_lines, hover=True)
    cursor.connect("add", on_hover)

# Create the toggle button
global button # do not remove-prevents garbage collection
button_axes = fig.add_axes([0.8885, 0.467, 0.1, 0.04])
button = Button(button_axes, label='Toggle 1,1 data')
button.on_clicked(lambda event: on_click(cursor))

# create the exit button
exit_button = ctk.CTkButton(window, text='Exit', command=window.destroy)
exit_button.pack(side='bottom')  # add the exit button to the window

# Show the plot
canvas.draw()
window.mainloop()
```

**Comment by anntzer** [comment]
You actually need to write `tk.BooleanVar(value=False)` for things to work, but I figured that out.

The bug turns out to be on your side: your on_click() function does not actually update the global cursor (the redefinition `cursor = mplcursors.cursor(...)` is only a local one), so all cursors from the second one actually stay there and never get removed, which leads to them overlapping with one another.  The easy fix would be something like
```python
def on_click():  # make this take no argument
    global cursor  # make this global
    show_y_new.set(not show_y_new.get())
    if show_y_new.get():
        for line in lines:
            if line.axes == axes[1, 1]:
                line.set_ydata(y_new[int(line.get_label().split(' ')[1])])
    else:
        for line in lines:
            if line.axes == axes[1, 1]:
                line.set_ydata(y[int(line.get_label().split(' ')[1])])
            
    valid_lines = [line for line in lines.values() if line.figure is not None]
    plt.draw()
    cursor.remove()
    cursor = mplcursors.cursor(valid_lines, hover=True)
    cursor.connect("add", on_hover)

# Create the button
global button # do not remove-prevents garbage collection
button_axes = fig.add_axes([0.8885, 0.467, 0.1, 0.04])
button = Button(button_axes, label='Toggle 1,1 data')
button.on_clicked(lambda event: on_click())
```
to make sure the global cursor gets updated.
